global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Linq;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Windows.Forms;
global using WiFiCast.Models;
global using WiFiCast.Services;
