global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using CopyPath.Services;
global using WpfFontFamily = System.Windows.Media.FontFamily;
global using DrawingColor   = System.Drawing.Color;
global using DrawingPen     = System.Drawing.Pen;
global using DrawingBrush   = System.Drawing.SolidBrush;
