using CrosswordCast.Models;

namespace CrosswordCast.Services;

public static class WordDatabase
{
    public static readonly List<WordEntry> All =
    [
        new("APPLE",   "빨간 사과"),
        new("ORANGE",  "주황 과일"),
        new("BANANA",  "노란 과일"),
        new("GRAPE",   "포도"),
        new("LEMON",   "신 과일"),
        new("PIANO",   "건반 악기"),
        new("TABLE",   "식탁, 테이블"),
        new("CHAIR",   "의자"),
        new("HOUSE",   "집"),
        new("WATER",   "물"),
        new("BREAD",   "빵"),
        new("MUSIC",   "음악"),
        new("DANCE",   "춤"),
        new("MOVIE",   "영화"),
        new("RIVER",   "강"),
        new("CLOUD",   "구름"),
        new("TRAIN",   "기차"),
        new("NIGHT",   "밤"),
        new("LIGHT",   "빛"),
        new("STONE",   "돌"),
        new("HEART",   "마음, 심장"),
        new("SMILE",   "미소"),
        new("DREAM",   "꿈"),
        new("GREEN",   "초록색"),
        new("OCEAN",   "바다"),
        new("SUGAR",   "설탕"),
        new("MAGIC",   "마법"),
        new("TIGER",   "호랑이"),
        new("EAGLE",   "독수리"),
        new("PEARL",   "진주"),
        new("PAPER",   "종이"),
        new("GLASS",   "유리"),
        new("HONEY",   "꿀"),
        new("STORM",   "폭풍"),
        new("ANGEL",   "천사"),
        new("PRISM",   "프리즘"),
        new("LOTUS",   "연꽃"),
        new("CROWN",   "왕관"),
        new("SWORD",   "검"),
        new("ARROW",   "화살"),
        new("TOWER",   "탑"),
        new("BRAVE",   "용감한"),
        new("SWIFT",   "빠른"),
        new("FROST",   "서리"),
        new("FLAME",   "불꽃"),
        new("SOLAR",   "태양의"),
        new("LUNAR",   "달의"),
        new("CORAL",   "산호"),
        new("MAPLE",   "단풍나무"),
        new("BIRCH",   "자작나무"),
        new("CEDAR",   "삼나무"),
        new("POLAR",   "극지의"),
        new("ROBIN",   "울새"),
        new("BLOOM",   "꽃이 피다"),
        new("SLATE",   "점판암, 슬레이트"),
        new("SPINE",   "척추"),
        new("TROUT",   "송어"),
        new("PLUMB",   "수직의"),
        new("GROVE",   "작은 숲"),
        new("SHALE",   "혈암"),
        new("GLOBE",   "지구본"),
        new("CRISP",   "바삭한"),
        new("BLAZE",   "불길"),
        new("GLEAM",   "희미한 빛"),
        new("CLOAK",   "망토"),
        new("NOBLE",   "고귀한"),
        new("GRASP",   "붙잡다"),
        new("TREMBLE", "떨다"),
        new("MIRROR",  "거울"),
        new("BRIDGE",  "다리"),
        new("FOREST",  "숲"),
        new("GARDEN",  "정원"),
        new("PLANET",  "행성"),
        new("SILVER",  "은, 은색"),
        new("WINTER",  "겨울"),
        new("SUMMER",  "여름"),
        new("SPRING",  "봄"),
        new("AUTUMN",  "가을"),
        new("CANDLE",  "촛불"),
        new("CASTLE",  "성"),
        new("DESERT",  "사막"),
        new("DRAGON",  "용"),
        new("ESCAPE",  "탈출"),
        new("FALCON",  "매"),
        new("GENTLE",  "온화한"),
        new("HARBOR",  "항구"),
        new("ISLAND",  "섬"),
        new("JUNGLE",  "정글"),
        new("KNIGHT",  "기사"),
        new("LANTERN", "등불"),
        new("MARBLE",  "대리석"),
        new("NEEDLE",  "바늘"),
    ];
}
