using System.IO;
using System.Text;
using LocaleForge.Models;

namespace LocaleForge.Parsers;

public class PoParser : ILocaleParser
{
    public LocaleFileFormat Format => LocaleFileFormat.Po;
    public string FileFilter => "PO 파일 (*.po)|*.po";

    public Dictionary<string, string> Parse(string filePath)
    {
        var result = new Dictionary<string, string>();
        var lines = File.ReadAllLines(filePath, Encoding.UTF8);

        string? currentMsgId = null;
        var sb = new StringBuilder();
        bool inMsgStr = false;

        foreach (var line in lines)
        {
            if (line.StartsWith("msgid "))
            {
                if (currentMsgId != null && sb.Length > 0)
                    result[currentMsgId] = sb.ToString();

                currentMsgId = UnquotePo(line[6..].Trim());
                sb.Clear();
                inMsgStr = false;
            }
            else if (line.StartsWith("msgstr "))
            {
                sb.Clear();
                sb.Append(UnquotePo(line[7..].Trim()));
                inMsgStr = true;
            }
            else if (line.StartsWith("\"") && inMsgStr)
            {
                sb.Append(UnquotePo(line.Trim()));
            }
        }

        if (currentMsgId != null && sb.Length > 0)
            result[currentMsgId] = sb.ToString();

        // msgid "" 는 헤더이므로 제거
        result.Remove(string.Empty);
        return result;
    }

    private static string UnquotePo(string s)
    {
        if (s.StartsWith('"') && s.EndsWith('"'))
            s = s[1..^1];
        return s.Replace("\\n", "\n").Replace("\\t", "\t").Replace("\\\"", "\"");
    }

    public void Save(string filePath, Dictionary<string, string> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Locale.Forge");
        sb.AppendLine("msgid \"\"");
        sb.AppendLine("msgstr \"\"");
        sb.AppendLine();

        foreach (var (key, value) in entries.OrderBy(e => e.Key))
        {
            sb.AppendLine($"msgid \"{QuotePo(key)}\"");
            sb.AppendLine($"msgstr \"{QuotePo(value)}\"");
            sb.AppendLine();
        }

        File.WriteAllText(filePath, sb.ToString(), new UTF8Encoding(true));
    }

    private static string QuotePo(string s) =>
        s.Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\t", "\\t");
}
