using System.IO;
using System.Text;
using LocaleForge.Models;

namespace LocaleForge.Parsers;

public class PropertiesParser : ILocaleParser
{
    public LocaleFileFormat Format => LocaleFileFormat.Properties;
    public string FileFilter => "Properties 파일 (*.properties)|*.properties";

    public Dictionary<string, string> Parse(string filePath)
    {
        var result = new Dictionary<string, string>();
        var lines = File.ReadAllLines(filePath, Encoding.UTF8);

        foreach (var line in lines)
        {
            var trimmed = line.TrimStart();
            if (trimmed.StartsWith('#') || trimmed.StartsWith('!') || string.IsNullOrWhiteSpace(trimmed))
                continue;

            var eqIdx = trimmed.IndexOf('=');
            var colonIdx = trimmed.IndexOf(':');
            int sepIdx;
            if (eqIdx < 0) sepIdx = colonIdx;
            else if (colonIdx < 0) sepIdx = eqIdx;
            else sepIdx = Math.Min(eqIdx, colonIdx);

            if (sepIdx < 0) continue;

            var key = trimmed[..sepIdx].Trim();
            var value = trimmed[(sepIdx + 1)..].Trim();
            result[key] = UnescapeProperties(value);
        }

        return result;
    }

    private static string UnescapeProperties(string s) =>
        s.Replace("\\n", "\n").Replace("\\t", "\t").Replace("\\\\", "\\");

    public void Save(string filePath, Dictionary<string, string> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Locale.Forge");
        foreach (var (key, value) in entries.OrderBy(e => e.Key))
        {
            var escaped = value.Replace("\\", "\\\\").Replace("\n", "\\n").Replace("\t", "\\t");
            sb.AppendLine($"{key}={escaped}");
        }
        File.WriteAllText(filePath, sb.ToString(), new UTF8Encoding(true));
    }
}
