using System.Globalization;
using System.Text;
using Quant.Lab.Core.Engine;

namespace Quant.Lab.Core.Reporting;

public static class HtmlReporter
{
    public static void Save(BacktestResult result, string outputPath)
    {
        var html = Render(result);
        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);
        File.WriteAllText(outputPath, html, new UTF8Encoding(false));
    }

    public static string Render(BacktestResult r)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!doctype html><html lang=\"ko\"><head><meta charset=\"utf-8\">");
        sb.AppendLine("<title>Quant.Lab Backtest Report</title>");
        sb.AppendLine($"<style>{Css}</style></head><body>");

        sb.Append("<h1>Quant.Lab — Backtest Report</h1>");
        sb.Append($"<p class=\"sub\">Strategy: <b>{Esc(r.StrategyName)}</b> · Period: {r.Equity[0].Date:yyyy-MM-dd} ~ {r.Equity[^1].Date:yyyy-MM-dd} ({r.Equity.Count} bars)</p>");

        sb.Append("<div class=\"grid\">");
        Card(sb, "Total Return", FormatPercent(r.Metrics.TotalReturn), r.Metrics.TotalReturn >= 0);
        Card(sb, "CAGR", FormatPercent(r.Metrics.Cagr), r.Metrics.Cagr >= 0);
        Card(sb, "Max Drawdown", FormatPercent(r.Metrics.MaxDrawdown), false);
        Card(sb, "Sharpe", r.Metrics.SharpeRatio.ToString("F2", CultureInfo.InvariantCulture), r.Metrics.SharpeRatio >= 0);
        Card(sb, "Trades", r.Metrics.TradeCount.ToString(), null);
        Card(sb, "Win Rate", FormatPercent(r.Metrics.WinRate), r.Metrics.WinRate >= 0.5);
        Card(sb, "Initial Cash", FormatMoney(r.Metrics.InitialCash), null);
        Card(sb, "Final Equity", FormatMoney(r.Metrics.FinalEquity), r.Metrics.FinalEquity >= r.Metrics.InitialCash);
        sb.Append("</div>");

        sb.Append("<h2>Equity Curve</h2>");
        sb.Append(EquitySvg(r.Equity));

        sb.Append("<h2>Trades</h2>");
        if (r.Trades.Count == 0)
        {
            sb.Append("<p class=\"sub\">No trades.</p>");
        }
        else
        {
            sb.Append("<table><thead><tr>");
            sb.Append("<th>#</th><th>Entry</th><th>Exit</th><th>Qty</th><th>Entry Px</th><th>Exit Px</th><th>P&amp;L</th><th>Return</th>");
            sb.Append("</tr></thead><tbody>");
            int i = 1;
            foreach (var t in r.Trades)
            {
                sb.Append($"<tr><td>{i++}</td><td>{t.EntryDate:yyyy-MM-dd}</td><td>{t.ExitDate:yyyy-MM-dd}</td>");
                sb.Append($"<td class=\"num\">{t.Quantity:N0}</td>");
                sb.Append($"<td class=\"num\">{t.EntryPrice:N0}</td>");
                sb.Append($"<td class=\"num\">{t.ExitPrice:N0}</td>");
                sb.Append($"<td class=\"num {(t.Pnl >= 0 ? "pos" : "neg")}\">{t.Pnl:N0}</td>");
                sb.Append($"<td class=\"num {(t.Return >= 0 ? "pos" : "neg")}\">{FormatPercent(t.Return)}</td>");
                sb.Append("</tr>");
            }
            sb.Append("</tbody></table>");
        }

        sb.Append("<h2>Config</h2>");
        sb.Append("<table class=\"kv\"><tbody>");
        sb.Append($"<tr><th>Initial Cash</th><td>{FormatMoney(r.Config.InitialCash)}</td></tr>");
        sb.Append($"<tr><th>Commission</th><td>{FormatPercent((double)r.Config.CommissionRate)}</td></tr>");
        sb.Append($"<tr><th>Tax</th><td>{FormatPercent((double)r.Config.TaxRate)}</td></tr>");
        sb.Append($"<tr><th>Slippage</th><td>{FormatPercent((double)r.Config.SlippageRate)}</td></tr>");
        sb.Append($"<tr><th>Liquidate at End</th><td>{r.Config.LiquidateAtEnd}</td></tr>");
        sb.Append("</tbody></table>");

        sb.Append("<p class=\"footer\">Generated by Quant.Lab</p>");
        sb.Append("</body></html>");
        return sb.ToString();
    }

    private static void Card(StringBuilder sb, string label, string value, bool? positive)
    {
        var cls = positive switch { true => "card pos", false => "card neg", _ => "card" };
        sb.Append($"<div class=\"{cls}\"><div class=\"lbl\">{label}</div><div class=\"val\">{value}</div></div>");
    }

    private static string EquitySvg(IReadOnlyList<EquityPoint> equity)
    {
        const int W = 1000, H = 320, padL = 70, padR = 20, padT = 20, padB = 40;
        var min = (double)equity.Min(p => p.Equity);
        var max = (double)equity.Max(p => p.Equity);
        if (Math.Abs(max - min) < 1e-9) max = min + 1;

        var sb = new StringBuilder();
        sb.Append($"<svg viewBox=\"0 0 {W} {H}\" class=\"chart\" preserveAspectRatio=\"none\">");
        sb.Append($"<rect x=\"{padL}\" y=\"{padT}\" width=\"{W - padL - padR}\" height=\"{H - padT - padB}\" class=\"plotbg\"/>");

        sb.Append("<polyline class=\"line\" points=\"");
        for (int i = 0; i < equity.Count; i++)
        {
            var x = padL + (W - padL - padR) * (double)i / Math.Max(1, equity.Count - 1);
            var y = padT + (H - padT - padB) * (1 - ((double)equity[i].Equity - min) / (max - min));
            sb.Append(x.ToString("F1", CultureInfo.InvariantCulture));
            sb.Append(',');
            sb.Append(y.ToString("F1", CultureInfo.InvariantCulture));
            sb.Append(' ');
        }
        sb.Append("\"/>");

        sb.Append($"<text x=\"{padL - 6}\" y=\"{padT + 12}\" class=\"axis\" text-anchor=\"end\">{max:N0}</text>");
        sb.Append($"<text x=\"{padL - 6}\" y=\"{H - padB}\" class=\"axis\" text-anchor=\"end\">{min:N0}</text>");
        sb.Append($"<text x=\"{padL}\" y=\"{H - padB + 18}\" class=\"axis\">{equity[0].Date:yyyy-MM-dd}</text>");
        sb.Append($"<text x=\"{W - padR}\" y=\"{H - padB + 18}\" class=\"axis\" text-anchor=\"end\">{equity[^1].Date:yyyy-MM-dd}</text>");

        sb.Append("</svg>");
        return sb.ToString();
    }

    private static string FormatPercent(double v) => (v * 100).ToString("F2", CultureInfo.InvariantCulture) + "%";
    private static string FormatMoney(decimal v) => v.ToString("N0", CultureInfo.InvariantCulture) + " KRW";

    private static string Esc(string s)
        => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    private const string Css = @"
:root { color-scheme: dark; }
body { font-family: 'Segoe UI', system-ui, sans-serif; background:#1a1a1a; color:#e0e0e0; margin:24px; max-width:1100px; }
h1 { margin:0 0 4px; font-size:22px; color:#fff; }
h2 { margin:28px 0 10px; font-size:16px; color:#cfd8dc; border-bottom:1px solid #333; padding-bottom:6px; }
.sub { color:#888; margin:0 0 18px; font-size:13px; }
.grid { display:grid; grid-template-columns:repeat(4, 1fr); gap:10px; }
.card { background:#222; border:1px solid #333; border-radius:6px; padding:12px 14px; }
.card .lbl { color:#888; font-size:11px; text-transform:uppercase; letter-spacing:0.5px; }
.card .val { font-size:20px; font-weight:600; margin-top:4px; }
.card.pos .val { color:#4caf50; }
.card.neg .val { color:#f44336; }
table { width:100%; border-collapse:collapse; font-size:13px; }
th, td { padding:6px 10px; border-bottom:1px solid #2a2a2a; text-align:left; }
th { background:#252525; color:#bbb; font-weight:600; }
td.num { text-align:right; font-variant-numeric:tabular-nums; }
.pos { color:#4caf50; }
.neg { color:#f44336; }
table.kv th { width:160px; background:#202020; }
.chart { width:100%; height:auto; background:#181818; border:1px solid #2a2a2a; border-radius:6px; }
.plotbg { fill:#181818; }
.line { fill:none; stroke:#4fc3f7; stroke-width:1.5; }
.axis { font-size:10px; fill:#888; }
.footer { margin-top:24px; color:#555; font-size:11px; text-align:right; }
";
}
